
FROM node:14 AS builder
WORKDIR /app
COPY ./package.json .
RUN yarn install
COPY . .
RUN yarn build

FROM nginx:latest
COPY ./nginx.conf /etc/nginx/nginx.conf
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/build .
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]