version: "3"

services:
  database:
    build: Database
    volumes:
      - ./Database/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  cache:
    command: redis-server --requirepass Ashwin@123
    image: redis
    ports:
      - 6379:6379

  backend:
    build: Backend
    depends_on: [database, cache]
    ports:
      - 8000:8000

  frontend:
    build: Frontend
    depends_on: [backend]
    ports:
      - 3000:80


  # backend:
  #   build: Backend
  #   depends_on: [database, cache]
  #   deploy:
  #     replicas: 5
  #   ports:
  #     -8000:8000